brandmooffin/cocos2d-mono

cocos2d/menu_nodes/CCMenuItemSprite.cs

#62 - Change color and opacity for images in CCMenuItems

---

cocos2d/menu_nodes/CCMenuItemSprite.cs

#55 - Allows CCMenuItemSprite to be initialized with CCTesture2D

---

cocos2d/textures/CCTexture2D.cs

Allows CCTextures2D to be created via string filename

---

cocos2d/tileMap_parallax_nodes/CCTMXMapInfo.cs

Add check for tsx file

---

box2d/box2d.Uwp/box2d.Uwp.csproj
cocos2d/cocos2d.Uwp/cocos2d.Uwp.csproj

Bump Windows 10 target to 10.0.20348.0

---

cocos2d/menu_nodes/CCMenu.cs
cocos2d/menu_nodes/CCMenuItemFont.cs
cocos2d/menu_nodes/CCMenuItemLabel.cs
cocos2d/textures/CCTexture2D.cs

- Add Support to Align Menu Items Left or Right Vertically - Fixes #184 
- Fix support for initializing CCSprite with CCTexture2D - Fixes #178 
- Support Change Text using Property for CCMenuItemFont - Fixes #186
- Add support for passing in fontname and fontsize for CCMenuItemFont - Fixes #187

update(CCMenu): CCMenu and CCTexture improvements

---

Tests/cocos2d-mono.Tests/cocos2d-mono.Tests.Android/cocos2d-mono.Tests.Android.csproj
Tests/cocos2d-mono.Tests/cocos2d-mono.Tests.iOS/cocos2d-mono.Tests.iOS.csproj
box2d/box2d.Android/box2d.Android.csproj
box2d/box2d.iOS/box2d.iOS.csproj
cocos2d/cocos2d.Android/cocos2d.Android.csproj
cocos2d/cocos2d.iOS/cocos2d.iOS.csproj
cocos2d/platform/CCDrawManager.cs

closes #177 
closes #191
closes #192

lowering minimum support os for android and ios

---

cocos2d/base_nodes/CCNode.cs
cocos2d/base_nodes/CCNodeRGBA.cs
cocos2d/cocoa/CCAffineTransform.cs
cocos2d/layers_scenes_transitions_nodes/transition/CCTransitionFade.cs
cocos2d/misc_nodes/CCRenderTexture.cs

Closes #206 
Closes #197 
Closes #196 
Closes #198 
Closes #205

update(ccnode): CCNode improvements and merge with CCNodeRGBA

---

cocos2d/label_nodes/CCLabel.cs

update(cclabel): add system font properties to CCLabel

---

cocos2d/sprite_nodes/CCSprite.cs

update(ccsprite): CCSprite improvements

---

cocos2d/cocoa/CCGeometry.cs

update(ccpoint): add IsNear function

---

cocos2d/sprite_nodes/CCSpriteFrame.cs

update(ccspriteframe): add contentsize ccspriteframe

---

cocos2d/actions/action/CCAction.cs
cocos2d/actions/action/CCFiniteTimeAction.cs

new(ccactionstate): add CCActionState

---

cocos2d/extentions/GUI/CCControlExtension/CCScale9Sprite.cs

update(ccscale9sprite): add CCSprite constructor to CCScale9Sprite 

---

cocos2d/predefine/ccTypes.cs

update(cccolor4b): add support for math operators

---

cocos2d/Math/CCMathHelper.cs
cocos2d/actions/action/CCFiniteTimeAction.cs
cocos2d/actions/action_intervals/CCColorBlendAnimation.cs
cocos2d/actions/action_intervals/CCMoveFrom.cs
cocos2d/actions/action_intervals/CCParallel.cs
cocos2d/actions/action_intervals/CCRotateAnimation.cs
cocos2d/actions/action_intervals/CCSwapAction.cs
cocos2d/actions/action_intervals/CCTargetedAction.cs
cocos2d/actions/action_intervals/CCTimerAction.cs
cocos2d/actions/action_intervals/ICCRotationAnimationGetter.cs
cocos2d/cocoa/CCGeometry.cs
cocos2d/cocos2d.projitems
cocos2d/misc_nodes/CCSwappableNode.cs

new(ccaction): add new ccactions

---

cocos2d/base_nodes/CCNode.cs
cocos2d/base_nodes/CCTapNode.cs
cocos2d/cocos2d.projitems
cocos2d/platform/CCRawList.cs

Closes #207 
Closes #212 
Closes #213

update(cctap): add CCTapNode

---

cocos2d/base_nodes/CCNode.cs
cocos2d/layers_scenes_transitions_nodes/CCLayer.cs

update(cclayer): add AddedToScene to CCLayer

---

cocos2d/sprite_nodes/CCSpriteFrame.cs
cocos2d/sprite_nodes/CCSpriteSheet.cs

update(ccspriteframe): Add TextureFilename to CCSpriteFrame

---

cocos2d/textures/CCTexture2D.cs

update(cctexture2d): Add CCTexture2D constructor for data byte array

---

cocos2d/extentions/GUI/CCControlExtension/CCScale9Sprite.cs
cocos2d/extentions/GUI/CCControlExtension/CCScale9SpriteFrame.cs

update(ccscale9sprite): Added constructors for init CCScale9Sprite by CCSpriteFrame

---

cocos2d/actions/action_ease/CCActionEase.cs
cocos2d/actions/action_ease/CCEaseBackIn.cs
cocos2d/actions/action_ease/CCEaseBackInOut.cs
cocos2d/actions/action_ease/CCEaseBackOut.cs
cocos2d/actions/action_ease/CCEaseBounceIn.cs
cocos2d/actions/action_ease/CCEaseBounceInOut.cs
cocos2d/actions/action_ease/CCEaseBounceOut.cs
cocos2d/actions/action_ease/CCEaseCustom.cs
cocos2d/actions/action_ease/CCEaseElastic.cs
cocos2d/actions/action_ease/CCEaseElasticIn.cs
cocos2d/actions/action_ease/CCEaseElasticInOut.cs
cocos2d/actions/action_ease/CCEaseElasticOut.cs
cocos2d/actions/action_ease/CCEaseExponentialIn.cs
cocos2d/actions/action_ease/CCEaseExponentialInOut.cs
cocos2d/actions/action_ease/CCEaseExponentialOut.cs
cocos2d/actions/action_ease/CCEaseIn.cs
cocos2d/actions/action_ease/CCEaseInOut.cs
cocos2d/actions/action_ease/CCEaseOut.cs
cocos2d/actions/action_ease/CCEaseRateAction.cs
cocos2d/actions/action_ease/CCEaseSineIn.cs
cocos2d/actions/action_ease/CCEaseSineInOut.cs
cocos2d/actions/action_ease/CCEaseSineOut.cs
cocos2d/actions/action_intervals/CCActionInterval.cs
cocos2d/actions/action_intervals/CCColorBlendAnimation.cs

update(cceaseactions): Add support for CCFiniteTimeAction for CCEaseActions

---

cocos2d/base_nodes/CCNode.cs
cocos2d/label_nodes/CCLabelBMFont.cs

fix(cclabel): Fixes for CCLabel resize when not visible

---

cocos2d/actions/action/CCAction.cs
cocos2d/actions/action/CCFiniteTimeAction.cs
cocos2d/actions/action_intervals/CCColorBlendAnimation.cs
cocos2d/actions/action_intervals/CCMoveFrom.cs
cocos2d/actions/action_intervals/CCParallel.cs
cocos2d/actions/action_intervals/CCRotateAnimation.cs
cocos2d/actions/action_intervals/CCSwapAction.cs
cocos2d/actions/action_intervals/CCTargetedAction.cs
cocos2d/actions/action_intervals/CCTimerAction.cs

Removed states

---

cocos2d/sprite_nodes/CCSprite.cs

maintain scale when changing spriteframe

---

cocos2d/base_nodes/CCTapNode.cs

return value for isswallowtouches

---

cocos2d/sprite_nodes/CCSprite.cs

fixes for updating contentsize

---

Tests/cocos2d-mono.Tests/ActionsTest/ActionsTest.cs
cocos2d/actions/action_intervals/CCSwapAction.cs
cocos2d/misc_nodes/CCSwappableNode.cs

Improvements for CCSwapAction

---

cocos2d/predefine/ccTypes.cs

add more colors

---

Tests/cocos2d-mono.Tests/DrawPrimitivesTest/DrawPrimitivesTest.cs
cocos2d/base_nodes/CCNode.cs
cocos2d/misc_nodes/CCDrawNode.cs
cocos2d/predefine/ccTypes.cs

fix node pause resume issue

---

cocos2d/label_nodes/CCLabel.cs

update font configuration when size changes

---

cocos2d/sprite_nodes/CCSprite.cs

Fix contentSize not setting when CCSprite is not visible

---

cocos2d/label_nodes/CCLabel-Android.cs
cocos2d/label_nodes/CCLabelUtilities-CoreGraphics.cs

adjust scaling for ios and line height android

---

.github/workflows/android_build.yml
Tests/cocos2d-mono.Tests/cocos2d-mono.Tests.Android/cocos2d-mono.Tests.Android.csproj
Tests/cocos2d-mono.Tests/cocos2d-mono.Tests.iOS/Info.plist
Tests/cocos2d-mono.Tests/cocos2d-mono.Tests.iOS/cocos2d-mono.Tests.iOS.csproj
box2d/box2d.Android/box2d.Android.csproj
box2d/box2d.iOS/box2d.iOS.csproj
cocos2d/cocos2d.Android/cocos2d.Android.csproj
cocos2d/cocos2d.iOS/cocos2d.iOS.csproj
cocos2d/text_input_node/CCTextFieldTTF.cs

update(CCTextField): implement textfield

---

cocos2d/label_nodes/CCLabel.cs

adjust position to reduce line artifacts on fonts

---

Tests/cocos2d-mono.Tests/SpriteTest/SpriteReset.cs
Tests/cocos2d-mono.Tests/SpriteTest/SpriteTestScene.cs
Tests/cocos2d-mono.Tests/cocos2d-mono.Tests.projitems
cocos2d/sprite_nodes/CCSprite.cs

Fix for texture disposing too early

---

cocos2d/label_nodes/CCLabel.cs

Recreate font config if missing on update

---

cocos2d/label_nodes/CCLabelBMFont.cs

add null reference checks

---

cocos2d/label_nodes/CCLabel.cs

Remove unnecessary font spacing reduction for iOS

Remove unnecessary font spacing reduction for iOS

---

cocos2d/denshion/CCSimpleAudioEngine.cs

Fixes C2D-99 C2D-97
Closes #405 #403

update(audio): pause & resume all sfx

---

cocos2d/base_nodes/CCNode.cs
cocos2d/extentions/GUI/CCControlExtension/CCControlButton.cs
cocos2d/menu_nodes/CCMenu.cs
cocos2d/menu_nodes/CCMenuItemLabel.cs
cocos2d/menu_nodes/CCMenuItemSprite.cs
cocos2d/menu_nodes/CCMenuItemToggle.cs

Fixes C2D-95 & C2D-96
Closes #401 
Closes #402

update(actions): streamline actions and menu align functions

---

cocos2d/sprite_nodes/CCSprite.cs
cocos2d/sprite_nodes/CCSpriteFrame.cs

remove originalsize

---

cocos2d/sprite_nodes/CCSprite.cs

removed IsFrameDisplayed
